/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

module rsr(clk, rst, r_in, r_out);
  input clk;
  input r_in;
  output r_out;
  input rst;
  assign r_out = 1'hx;
endmodule
